# Generated by Django 5.1.3 on 2025-02-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0012_reply_parent_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
