# Generated by Django 5.1.3 on 2025-02-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0013_reply_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='a_posts.comment'),
        ),
    ]
