# Generated by Django 5.1.3 on 2025-02-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_landingpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='access_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
